# Generated by Django 4.2.25 on 2026-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('source_job_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('job_hash', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skills', models.TextField(blank=True)),
                ('external_apply_link', models.URLField(max_length=1000)),
                ('employment_type', models.CharField(blank=True, max_length=100)),
                ('salary_range', models.CharField(blank=True, max_length=255)),
                ('experience_years', models.CharField(blank=True, max_length=100)),
                ('company_logo', models.URLField(blank=True, max_length=1000)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('visa_type', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('is_reviewing', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
